### ISSUE TITLE
[MAC] mic stopped working completely on recent builds

### ISSUE THREAD

**Issue by trulytrunity** [TASEmulators/desmume#475]
So my mic has not been working for any of my games, and I only just updated tonight. It was working great on my previous one and my mic works on the rest of my programs, just not desmume. I tried uploading an audio file because the defaults weren’t working, like I used a hot key, tried using my actual mic as it’s worked before, but nothing. The NDS mic volume doesn’t change. it won’t pick anything up, despite all the solutions. I’ve tried redownloading it, tried editing and resetting the configurations. I’ve changed the hot key. I’ve used the white noise. I’ve used an audio file. I’ve used the defaults. The NDS mix just refuses to change or pick anything up.

**Comment by zeromus** [comment]
What does "I only just updated tonight" mean? Did your mic work before tonight?

**Comment by trulytrunity** [comment]
> What does "I only just updated tonight" mean? Did your mic work before tonight?

yes, it did. I hadn’t updated in a while until last night, and it worked before I updated, but stopped working after I did update.

**Comment by zeromus** [comment]
Updated what? From what, to what?

**Comment by trulytrunity** [comment]
Updated my old version of desmume to the most recent update of desmume. I
don’t remember what the old one’s numbers were because it’s been a while
since I originally downloaded it. I updated the program because I updated
my Mac OS, again to the most recent update and it didn’t want to run the
older version of desmume.
Sorry if I’m being unclear, English isn’t my first language.

**Comment by trulytrunity** [comment]
> Updated what? From what, to what?

Updated my old version of desmume to the most recent update of desmume. I don’t remember what the old one’s numbers were because it’s been a while since I originally downloaded it. I updated the program because I updated my Mac OS, again to the most recent update and it didn’t want to run the older version of desmume.  
Sorry if I’m being unclear, English isn’t my first language.

**Comment by zeromus** [comment]
Previously when it worked, were you using the actual mic or were you using a sound file?

**Comment by trulytrunity** [comment]
> Previously when it worked, were you using the actual mic or were you using a sound file?

I would use my actual mic. I didn’t have any issue with it prior to this, so I never attempted the sound files until the most recent version of desmume.

**Comment by rogerman** [comment]
The reason why the microphone doesn't work is due to changes with how Xcode 12 handles user entitlements, of which the microphone is one of them. Previous Mac DeSmuME builds Mac were built with Xcode 9, which wasn't nearly as strict. Recent Mac DeSmuME builds were built with Xcode 12, which has greatly increased the strictness of how apps are built. Getting around Xcode 12 (and later Xcode) shenanigans is currently an area of research.

To that end, the other mic options that are activated via hotkeys should still continue to work.

**Comment by rogerman** [comment]
So the main issue here is that macOS v10.14 Mojave, which enforces permissions on audio-visual devices like the microphone. See this for more details: https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture_on_macos?language=objc

Xcode 9 uses the macOS v10.13 SDK, which is why building DeSmuME with that would ignore microphone permissions. But Xcode 10 uses macOS v10.14 SDK, which forces all of this whole microphone permissions nonsense.

As of commit efa72df, users running Mojave or later will see a one-time permissions request upon starting a ROM. While this commit fixes the immediate issue of microphone access, it's not the most ideal solution. What should actually happen is this stuff:

1. Microphone permissions should be requested at app startup.
2. The CoreAudioInput class, which is what handles hardware microphone input, needs to handle the lack of permissions more gracefully.
3. If the user denies permission, then there needs to be a method within the app where the user can request microphone permission again. In addition, if the user grants permission, then there needs to be a method within the app where the user can deny microphone permission after the fact. The user should be able to freely switch microphone permissions between granted and denied at any time.
4. New icons are required to reflect that microphone permission is denied as opposed to simply being off.

**Comment by rogerman** [comment]
Commit a73705bc finalizes this work. Items 1, 2, and 4 have been fully implemented.

Item 3, for which the user can freely grant or deny microphone permissions during real-time execution, is not possible. Apple only allows apps to grant microphone permission just once, and any subsequent changes to permissions must occur through System Preferences instead of through the app. Therefore, mouseover tooltips have been added to the Microphone Settings panel to guide the user in how to change permissions if they chose to deny permission at app startup. Of course, since the CoreAudioInput class can now handle changes in permission state much better than ever before, the user experience for dealing with Mac DeSmuME's microphone permissions should be completely seamless.

I can now say that all of the UI and behaviors concerning the issue of microphone permissions are now feature complete.
