### ISSUE TITLE
Layer Issue

### ISSUE THREAD

**Issue by abx-dx** [TASEmulators/desmume#486]
There is Pokéstar Studios at game of Pokémon Black 2. When you go to cinema, you can watch the movie you recorded before.

After version 0.0.0.876 i can't watch cinema properly, seems one or more layer is missing at game. I'm trying to keep Desmume updated from AppVeyor but the problem still exists. For example it can be seen at screenshots i used v0.0.0.876 and v0.0.0.893. Game is not patched or corrupted (SHA-1 verified). I'm using same .ini file for both versions. I'm using Windows 10 x64 with Mobile Intel(R) 4 Series Express Chipset Video Driver.

![image](https://user-images.githubusercontent.com/89312500/140616099-74762882-3af4-4b3e-93e7-4a50ad65c803.png)
![image](https://user-images.githubusercontent.com/89312500/140616132-f8571b21-8b56-428c-a687-70d9e050906e.png)
![image](https://user-images.githubusercontent.com/89312500/140616344-75de757c-8952-4732-b081-0a8ea663fc38.png)

**Comment by zeromus** [comment]
@rogerman seems this was most likely due to the GPU window commits around that time?

**Comment by abx-dx** [comment]
At next update v0.0.0.877, rogerman had written: "GPU: Only perform window testing when the relevant window states actually change."

**Comment by rofl0r** [comment]
since there's a known (and small) range of good and bad versions in this case, it's probably straight-forward to find the commit introducing the issue quickly via `git bisect`.

**Comment by tuzepoito** [comment]
Does anyone have a Windows build for v876? I might compare with my own [issue](https://github.com/TASEmulators/desmume/issues/487).

**Comment by rogerman** [comment]
This issue has nothing to do with issue #487, which was simply a misconfiguration of the CPU emulation options by the user. But could this issue be caused by commit 7fc2e4b? Possibly.

The easiest way to solve is get the steps to reproduce from @abx-dx and test. For testing, we will need either:
1. A .dsv battery save file for the game, preferably saved at a point that is close to Pokéstar Studios.
2. A .dst save state file before entering the cinema.

AFAIK, all cases where window testing is required have been covered. If this issue is truly a case of a missing window test, then Pokémon Black 2 must be doing something very strange here.

**Comment by abx-dx** [comment]
Hello again,

This time i used v0.0.0.894 (again failure) and got a .dsv, a .ds0 and a .dst file (.dst was in backup folder). .dsv has taken at gate of cinema, .ds0 has taken before choosing a movie (just need to press A to proceed). i don't know what .dst holds since it is backup data.

@rogerman i couldn't upload here, if you recommend a file upload service which you trust i'll send link of them or i can send e-mail to you.

**Comment by rogerman** [comment]
@abx-dx, you can upload the files to this link:
https://www.dropbox.com/request/wRFvuquXxGIMhBiXg0KK

**Comment by abx-dx** [comment]
Just uploaded.

At Bulbapedia it's written: "Black 2 and White 2 are also the final first-party games for the Nintendo DS family of systems.". So they should get full advantage of Nintendo DS.

**Comment by zeromus** [comment]
what does that even mean?

**Comment by abx-dx** [comment]
I mean, since this game is the final first-party game they should use all potential of both hardware and software. @rogerman mentioned if this issue is truly a case of a missing window test, then Pokémon Black 2 must be doing something very strange here.

**Comment by rogerman** [comment]
So the ultimate problem wasn't that the window test wasn't running (it ran perfectly every time it needed to), it was that the test data produced by the window test wasn't getting updated properly. Since this window test data is used to determine whether pixels are drawn or not, failing to update the test data is what caused the black screen described by this issue.

Commit 7fc2e4b6 introduced a newer and more efficient window test system that changed the way various window test checks were done. Under the old system, these checks were scattered in various places and would even run uselessly under certain conditions. This caused very noticeable performance drops, especially when running at high GPU scaling factors. For example, reading a sign in Super Mario 64 DS would cause the game to lag heavily. But under the new system, all the window test checks have been gathered in one place, and the window test runs only when needed. The performance increase with the new window test system is substantial.

So why did Pokemon Black 2 fail where other games did not? The reason is because the WIN0H and WIN1H registers, which are used to generate the window test data, are normally changed along with all of the other window test registers, and so the window test ran fine with those games. However, Pokemon Black 2 sets WIN0H and WIN1H in advance, and so when all the window test states are finally checked in GPUEngineBase::_PerformWindowTesting(), WIN0H and WIN1H could end up being ignored if the only register changes were to WIN0_ENABLED or WIN1_ENABLED, which is exactly what Pokemon Black 2 does.

The old checks for WIN0_ENABLED and WIN1_ENABLED in GPUEngineBase::_UpdateWINH() prevented the window test data from being updated. Since these checks have now been superceded by the new window test system, they have been removed to allow _UpdateWINH() to update the window test data properly.

**Comment by abx-dx** [comment]
I confirm it works now! Thanks @rogerman
