### ISSUE TITLE
" The emulation has halted due to an internal issue. "

### ISSUE THREAD

**Issue by milkykissu** [TASEmulators/desmume#561]
[ BEGIN DESMUME TROUBLESHOOTING INFORMATION ]

App Version:  0.9.13 x64 SSE4.2+AVX2 (LLVM-Clang v13.1.6)
Operating System: Mac OS X v10.13.1 (17B1003)
Model Identifier: MacBookPro14,1
ROM Name: POKEMON B2
ROM Serial: TWL-IREO-INT

Emulation Speed: 1.00x
Auto Frame Skip: YES
SLOT-1 Device Type: Retail (Auto)
SLOT-2 Device Type: Auto
Advanced Bus-Level Timing: NO
Rigorous 3D Rendering Timing: NO
CPU Emulation Engine: Interpreter
Use Game-Specific Hacks: YES
External BIOS: NO
External Firmware: NO
GPU - Scaling Factor: 1x
GPU - Color Depth: 18-bit
3D Renderer - Engine: SoftRasterizer (HighResColor=YES, LineHack=YES, FragmentSamplingHack=NO, ThreadCount=Automatic)
3D Renderer - Enable Textures: YES
3D Renderer - Texture Deposterize: NO
3D Renderer - Texture Scaling Factor: 1x
3D Renderer - Edge Marking: YES
3D Renderer - Fog: YES
Video - Output Engine: macOS Metal GPUFamily1_v3 (Intel(R) Iris(TM) Plus Graphics 640)
Audio - Output Engine: macOS Core Audio Sound Interface
Audio - Advanced SPU Logic: YES
Audio - Sound Interpolation Method: Cosine
Audio - Sound Synchronization Method: Dual SPU Sync/Async

Cheats: NO

Observed Behavior: When I was fighting Zekrom (N) but about to lose, I reset the game in order not to lose any money ( Before that I had already saved the game, in case I want to do something again ). But when I reset it and boot the game, clicking on “ Continue “ to resume my journey, the game crashes and it said the emulator halted due to internal issue. However, when I clicked on the “ New game “, it still let me play the game normally, albeit from the start. 

Expected Behavior: I don’t want to lose the playing progress neither restart everything from the beginning. Please help me fix it up without deleting the saved file. Thank you. 

[ END DESMUME TROUBLESHOOTING INFORMATION ]

**Comment by rogerman** [comment]
As a note to us developers, this error message is sent from Mac DeSmuME whenever the 'execute' flag is set to false during program execution.

For you, whenever this particular error occurs, this usually means that the emulator tried to execute some undefined CPU instruction. The error should then list some info about the program counter location, which instruction it tried to run, and the address of said instruction in emulated memory.

So what does this all mean? Almost always, the emulated memory from which the CPU instructions run from was corrupted, and this almost always occurs when utilizing cheats. Cheats by their very nature are designed to 'corrupt' game memory in your favor. Your troubleshooting reports says that you didn't have any cheats activated at the time of the report, but it is possible that using cheats beforehand could have corrupted emulated memory, then using save states afterwards preserved that memory corruption, even after turning the cheats off.

Unfortunately, there is no way to recover from this scenario unless you have a save state that can restore your game from before you used your cheats. The lesson to learn here is to be very careful when using cheats and/or save states, especially when using them in tandem. If you do so, maintain plenty of backup files just in case something goes wrong.

Closing, due to what is most likely a user error. The assumption here is that you abused cheats and/or save states by using them in an improper manner. But if, in fact, you did not use cheats or save states even once during your entire game run, then we can reopen this ticket.
