### ISSUE TITLE
[macOS, ARM] Redundant Settings Menu

### ISSUE THREAD

**Issue by highwayscooper** [TASEmulators/desmume#573]
DeSmuME v0.9.13

Emulation settings listed under the DeSmuME preference panel do not affect the emulation, while the individual settings listed under the 'Emulation' tab of the program do. 

They don't mirror each other's configuration either; for example, if you change the internal rendering resolution in the '3D Rendering Settings' panel in the 'Emulation' tab to 3x, it will stay at 1x in the preference panel.

Having two ways of doing the same thing doesn't make any sense.

**Comment by rogerman** [comment]
The settings in DeSmuME Preferences are the default settings that the app uses on startup.

The settings in the individual settings panels in the Emulation menu reflect the current settings that are used during the app session.

Therefore, they are NOT supposed to do the same thing, and they are NOT supposed to mirror each other. It's supposed to work with the user changing the settings in real time via the settings panels in the Emulation menu, and once the user is happy with the settings, they can click "Save Settings as Default" to make those settings the defaults, as reflected in DeSmuME Preferences.

This is a very deliberate design choice that is not going to change, as this is the norm for how most Mac apps behave. Closing, due to the user's misunderstanding on typical Mac app behavior.
