### ISSUE TITLE
Load User Settings from file is broken?

### ISSUE THREAD

**Issue by Priestyle** [TASEmulators/desmume#577]
I want to launch the game in manual mode through the DS menu screen. I use my own firmware from my ds which has manual boot mode. I checked load user settings from file but the game always starts directly. I'm not sure what's going on. Is it a problem on my end?

**Comment by rogerman** [comment]
It seems like you want to use an external firmware file, rather than using DeSmuME's fake firmware. To do so, you'll need all of the following:
1. An NDS ARM9 BIOS file
2. An NDS ARM7 BIOS file
3. An NDS firmware file (seems like you already have this)
4. In your Emulation settings, "Use external BIOS images" and "Use external firmware" are both enabled

Only when you have all of these files present and these emulation options enabled can you use your own firmware user settings. Can you confirm that you have done all of the things listed above?

**Comment by Priestyle** [comment]
Yes I have confirmed that I have done all 4 things that you listed

**Comment by rogerman** [comment]
Then it should be working as intended.

Keep in mind that the "Boot from firmware" and "Load User Settings from file" options are two completely separate options. It is possible to load external firmware settings without booting into the firmware, and it is also possible to boot into firmware while loading DeSmuME's internal firmware settings.

Are you using the enabling the correct firmware options in your Emulation settings?

**Comment by Priestyle** [comment]
I'm sorry, this was a misunderstanding on my end. Please close this issue. The feature works as intended.

**Comment by Priestyle** [comment]
I have a video of the problem because i don't know how to describe it:

https://dl.dropboxusercontent.com/s/b8k7z3nwu0xp4h4/record-2022-08-09_10-56-09.mp4

**Comment by zeromus** [comment]
So you're using a tool to hack the firmware. Try skipping that step.
Despite the bevy of customized options you've chosen (WHY??? try resetting everything to do a thorough test) my firmware works just fine (it does not show the NDS splash screen though but rather boots straight to the firmware, huh. I'm not sure I've ever seen that screen before. We may be booting it wrongly, but I'm not sure).

**Comment by Priestyle** [comment]
The reason you don't see the NDS splash screen is because your firmware was modified. A regular ds firmware shows that screen in a real ds console

**Comment by zeromus** [comment]
if you're such an expert on firmware modifications then you wouldn't have a firmware that boots straight to the game. i'm up to my ears in firmwares that boot to the home menu (and skip the splashscreen) :shrug:

**Comment by rogerman** [comment]
> when I untick load user settings from file, it goes to the ds menu screen but it uses the internal desmume firmware.
Yes, yes, yes, this is exactly how it is supposed to work. You just said that you unticked "Load user settings from file". You also kept "Boot from firmware" ticked. So what did DeSmuME do? 


> But for some reason, with desmume, the firmware changes from its original state/settings or something
Yes, yes, yes, this is what DeSmuME is supposed to do. DeSmuME is now using its own internal firmware settings, which can be set in "Config > Firmware Settings". Things are working exactly as intended.


> i'm not sure what's going on
??? You just described everything that just went on, and everything is working as intended. I'm very confused with what you were expecting the firmware settings to do here.

**Comment by Priestyle** [comment]
Oh I thought ticking Load user settings from file in DeSmuME settings means that i get to use the settings of my own firmware like how i editted the settings of the firmware using a tool -- for example, the manual boot settings. My question is, is it not possible to use my own firmware.bin with my own personal settings with DeSmuME? (again, for example, the manual boot settings that I set to) i'm sorry i feel like i'm being redundant here

**Comment by rogerman** [comment]
@Priestyle: The "Load user settings from file" uses the firmware settings that are DERIVED from the firmware.bin file, as shown in the emulated NDS firmware boot menu. The actual firmware.bin settings are saved in the "firmware.dfc" file in DeSmuME's Battery directory. DeSmuME DOES NOT use nor require any editted settings from any third-party tools, since DeSmuME handles all of those things on its own.

Here's how the settings work.

"Boot from firmware" option: Controls whether the emulated NDS uses the firmware boot menu or simply starts the game straightaway. There is no reason to write "manual mode" to the firmware.bin file because DeSmuME will ignore it and use its own "Boot from firmware" option instead.

"Load user settings file" option: When disabled, the NDS firmware will use DeSmuME's internal firmware settings, configured through "Config > Firmware Settings." When enabled, the NDS firmware will derive its firmware settings from firmware.bin and save those settings to a config file named "firmware.dfc" in the Battery directory. Again, there is no need to use any third-party tools to write directly to the firmware.bin file since these settings are already controlled through the emulation itself.**


** There is an exception to this: In the Mac port, you can configure the WiFi MAC address, but on all other ports, you cannot do this. This is a limitation on the non-Mac ports, and so you may need that third-party tool to configure a new MAC address directly in firmware.bin if you need to do so.

**Comment by Priestyle** [comment]
ok i get it now thank you so much for the answer, how do i edit the firmware.dfc file then? sorry if this is a dumb question

**Comment by rogerman** [comment]
> ok i get it now thank you so much for the answer, how do i edit the firmware.dfc file then? sorry if this is a dumb question

By booting into the firmware (by enabling "Boot from firmware") and configuring the firmware settings within the emulated environment -- just like how you would do it on a hardware NDS. DeSmuME automatically handles reading/writing the firmware.dfc file, so there is no need to edit it directly.
