### ISSUE TITLE
Speed up not working

### ISSUE THREAD

**Issue by Sahmoke** [TASEmulators/desmume#619]
Playing pokemon diamond and whenever I use the speed up it barely speeds up and creates stutters. Looking for a fix or whatever can help

**Comment by zeromus** [comment]
your computer is too slow.

**Comment by Sahmoke** [comment]
> 

My pc runs star citizen lol how does that make any sense?

**Comment by zeromus** [comment]
This emulator is more demanding than one of the most demanding games on the market. Desmume has to run every nds game. Star citizen has to run star citizen. Doing everything is harder than doing one thing.

**Comment by Sahmoke** [comment]
So it is the code that is the issue and not my pc LOL. When its running a single game on my computer its not trying to run every game. Its doing one thing and not multiple things. So where do you think the issue is? Careful you might have to use your brain for this one.

**Comment by Sahmoke** [comment]
and yea I know im being a bit of an ass but I went through and read alot of your other "completed" issues and you seem like a very lazy and bitter individual so I think you'll be alright.

**Comment by zeromus** [comment]
I didn't say it IS running every game, nor that it IS running every game at once. I said it HAS to run every game, meaning its internal operations have to be generalized to support every case instead of just what one game needs. I'm done giving you a tutorial on computing now.

**Comment by rogerman** [comment]
@Sahsmoke, you may not believe it, but Star Citizen is not as nearly as sophisticated as you think it is. Star Citizen, like most modern games, are more GPU dependent, while emulators, especially NDS emulators like DeSmuME, are almost all CPU dependent. In particular, the NDS graphics hardware is unique and doesn't work like how modern PCs do it, which forces us to use much CPU in order to maintain compatibility with games. Therefore, the measuring stick that you're using to judge what a "demanding game" is is already incorrect out of the gate.

According to the Star Citizen recommended system requirements:
https://support.robertsspaceindustries.com/hc/en-us/articles/360042417374-Star-Citizen-Minimum-System-Requirements

This game only requires an Intel Sandy Bridge CPU, which is Intel's 2nd generation Core-series CPU from 2011. Also, Star Citizen recommends a 4GB VRAM GPU, which is something that can be achieved by a GeForce GTX1060 from 2016. These are hardly high system specs by any means.

According to the Star Citizen performance telemetry page:
https://robertsspaceindustries.com/telemetry

Running 1080p, High graphics settings, with the recommended hardware settings, you should be getting 30-39 FPS, which is playable. I've even read a few Reddit posts that confirm this exact setup. Therefore, I would hardly call Star Citizen "one of the most demanding games on the market." But this situation is pretty common with modern games, which again, are not as sophisticated as you might think. For example, Tiny Tina's Wonderlands, a game from 2022, has similar recommended system requirements, where the only difference is that Tiny Tina's recommends a 4th-generation Core-series CPU from 2014 (Haswell), rather than Star Citizen's 2nd-gen Sandy Bridge.

In DeSmuME's case, the few areas where a strong GPU can possibly help still require enormous amounts of CPU to support the GPU. This is by design, in order to maintain compatibility with the myriad of games in the full NDS library of games. We don't have the luxury of crafting a game engine and cutting corners with it to boost performance, erstwhile forcing the game designers and artists to work around the game engine's built-in limitations. In DeSmuME's case, it is the exact opposite: We have to make a very generalized emulation engine to account for ALL possible cases that an NDS game could throw at it, which greatly increases the emulator's complexity and naturally lowers performance. DeSmuME must respect compatibility. Emulation is a very different animal from modern gaming. This is even moreso with emulating the NDS, with its unique graphics hardware that is quite incompatible with modern PC graphics.

So it probably is your DeSmuME configuration at fault. Most likely, you're raising the graphics settings in DeSmuME higher than your hardware can handle without considering the CPU dependency on DeSmuME's graphics engine. For the record, I can run Pokemon Diamond at 4x speed quite easily on my 2009 Intel Core 2 Duo 3.06 GHz. Yeah, it drops some frames at 4x speed because it is a Core 2 Duo, but that's to be expected. On my i7-2860QM 2.5GHz Sandy Bridge, it doesn't drop frames at all when running running at 4x.

If you have an older CPU like my Core 2 Duo and my Sandy Bridge, trying some of these speed up tricks will help:
https://wiki.desmume.org/index.php?title=Faq#DeSmuME_runs_too_slow.21

For Pokemon Diamond in particular, turning on Dynamic Recompiler in your Emulation Settings will help a lot.
