### ISSUE TITLE
DPP DS Emulator

### ISSUE THREAD

**Issue by MagikarpSolo** [TASEmulators/desmume#684]
The traps in the Underground that require you to blow into the microhpone for are impossible to get out of lmao do I just need to download a different version of the game and play both at the same time to avoid softlocks?

**Comment by zeromus** [comment]
I don't know what DPP DS is. But the solution is most likely "google for other people playing this game on desmume to see what they say about mic samples which can get you past this scene". I'm not sure what you think "different version of the game" is going to do to help you do, but it makes it sound like you're cheating and hacking, so I'm presumptively voiding your warranty.

**Comment by Jules-A** [comment]
Pretty sure I remember recording myself blowing in to the mic and saving it as a wav and then selecting that in the microphone settings but you can probably find a sample easy enough on the internet and use that instead.
Zeromus, he was referring to Pokemon Diamond/Pearl/Platinum. By different game I think he means Pearl instead of Diamond for example.

**Comment by zeromus** [comment]
OK, but I still have no idea how you play both at once or how that helps you avoid softlocks.
