### ISSUE TITLE
Arrow Keys

### ISSUE THREAD

**Issue by Lucasbtd2008** [TASEmulators/desmume#721]
There is an issue where I am unable to move at all with the arrow keys. It started yesterday randomly while I was playing a Pokemon Platinum ROM and I could not move at all and for some reason, it still has not changed. This issue is also occurring with my other emulator for GBA games called mGBA. Can someone help me try to figure out what's wrong?

**Comment by zeromus** [comment]
third party hotkey managers and gamepad drivers may cause this. also you may be using "arrow keys" on the numpad and hitting numlock which makes them function as numbers instead of arrows. also you may be using a laptop with glitchy keyboard drivers (or you may be inadvertantly hitting some special laptop function key which does something similar to numlock)
