### ISSUE TITLE
please add desmume on snapcraft package

### ISSUE THREAD

**Issue by amidevous** [TASEmulators/desmume#765]
please add desmume on snapcraft package

https://snapcraft.io/search?q=desmume

We couldn't find anything for your search
desmume.
Try using some different, or more general keywords.

other all nitendo emulator found

Emulator for GB GBC GBA 

Visualboy Advance

official web site

https://visualboyadvance.org

found on snapcraft

https://snapcraft.io/search?q=visualboyadvance-m

easy install

sudo snap install sudo snap install visualboyadvance-m

Emulator for NDS (desmume not found on snapcraft please add)

Emulator for 3DS

Citra Emu

official web site

https://citra-emu.org/

found on snapcraft

https://snapcraft.io/search?q=citra-emu

easy install

sudo snap install sudo snap install citra-emu

Emulator for Switch

Yuzu

official web site

https://yuzu-emu.org/

found on snapcraft

https://snapcraft.io/search?q=yuzu

easy install

sudo snap install sudo snap install yuzu

please add desmume on snapcraft for add easy install NDS Emulator for all linux

**Comment by rofl0r** [comment]
why not use `apt` ? if the built-in repositories of your distro seem too outdated, switching to another distro is an option too. i heard that voidlinux has the newest package versions of everything. snap is basically just a bloated alternative to apt, in that only ubuntu users use it and everything is packaged with a complete set of libraries put into a sort of container, ignoring the packages you already have installed. so a "snap" of desmume would ship its own copy of gtk3, even though you already have it installed, therefore wasting your precious hdd space. apart from that, snaps only work on x86_64 linux distros with a compatible GLIBC versions, so your claim "runs on all linux" is pretty wild.

**Comment by andykimpe** [comment]
solve

[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/desmume-emulator)

https://github.com/TASEmulators/desmume/pull/767

**Comment by binocry** [comment]
> solve
> 
> [![Get it from the Snap Store](https://camo.githubusercontent.com/2c59b03ae976fd0e65789f40dada889afea9b3c4e6d9ba473576c8ef56855434/68747470733a2f2f736e617063726166742e696f2f7374617469632f696d616765732f6261646765732f656e2f736e61702d73746f72652d626c61636b2e737667)](https://snapcraft.io/desmume-emulator)
> 
> #767

Desmume refuse to open in Ubuntu 24.04.1

## State your operating system:
Ubuntu 24.04.1 LTS

## DesMuME version
0.9.13

## Issue
snap from DesMuME refuses to open, this is a report from the terminal with the command "snap run desmume-emulator"

snap run desmume-emulator
ALSA lib conf.c:4553:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
Failed to open device: No such file or directory
Microphone init failed.
DeSmuME 0.9.13 git#0 x64-JIT SSE2
CPU mode: Interpreter
Gtk-Message: 09:44:05.803: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Connection ":1.153" is not allowed to own the service "org.desmume.DeSmuME" due to AppArmor policy

(desmume:6258): GLib-CRITICAL **: 09:44:06.020: g_key_file_free: assertion 'key_file != NULL' failed

**Comment by rofl0r** [comment]
we don't support snaps. take this to your distro tracker or report the issue to whomever provided the snap.

**Comment by binocry** [comment]
> we don't support snaps. take this to your distro tracker or report the issue to whomever provided the snap.

I try to quote reply andykimpe not you
