### ISSUE TITLE
Search bar for cheats database

### ISSUE THREAD

**Issue by random42** [TASEmulators/desmume#824]
## State your operating system:
Mac

## DesMuME version
0.9.13

## Issue
Please make a search bar when adding cheats from the cheats database. It is awful to scroll through 2000 items to search stuff. Thank you and good work!

**Comment by rogerman** [comment]
Ever since commit e316711, the Cheat Database Viewer has been revamped to include a search feature, among many other features to make cheat database files much nicer to browse and use. Just download any recent nightly build if you want to check it out for yourself.

Closing, since this feature is already implemented.
