### ISSUE TITLE
Feature Request - Increase the resolution of the screenshots + one small thing

### ISSUE THREAD

**Issue by Felipefpl** [TASEmulators/desmume#832]
## State your operating system:
Windows 10

## DesMuME version
0.9.13 nightly

## Isse
Right now the resolution of the screenshots is mostly 256x384 which is too small to see on windows photo viewer:
![2024-09-12 10_48_51-Greenshot](https://github.com/user-attachments/assets/f86756fb-5e27-483b-8f0a-d1f97b0a87e8)

Also, when you display the pics in sequence in a section for screenshots like the one that nexus mods has https://www.nexusmods.com/pillarsofeternity/mods/12 the quality of the image is kinda compromised, it's not as good as it should be.

The small thing is: right now desmume doesnt offer an explanation of what the "GPU Scaling Factor" and other settings on 3D settings do, i searched the wiki and there is no info about this there or in the main site.

**Comment by zeromus** [comment]
1. no, and never. ask chatgpt for what 
2. Split this out on another ticket, and expect it to never get addressed. Designing info-boxes in windows resources is really hard work. Feel free to do your own investigation and post suggested content for the faq.

**Comment by zeromus** [comment]
1. you are the only person in the world who wants this. if we did this, every other single person would be upset by having to scale it back down to 1x before _doing their job of processing their 1:1 screenshots themselves_
2. This sentence makes no sense. If "there" is the wiki, then you just asked "why write a wiki if no wiki will be written" and if "there" is "info-boxes in windows resource" then the answer is trivially "because if it can't be in one place then maybe it could be in another"
