### ISSUE TITLE
No OpenGL renderer on Linux

### ISSUE THREAD

**Issue by petran79** [TASEmulators/desmume#856]
I am on OpenSUSE. Tried Flatpak version but it had only Software renderer. 
Tried to compile from source for a newer version following the guide, same issue. OpenGL is missing from graphics menu.

Is there a specific argument or devel library missing to enable OpenGL during compile or is it for the time being disabled on Linux?

**Comment by rogerman** [comment]
Exactly what guide were you following so that OpenGL didn't appear as an option?

If you follow our guide and use one of these Build Configuration Examples, then OpenGL should be an option:
[http://wiki.desmume.org/index.php?title=Installing_DeSmuME_from_source_on_Linux#Build_Configuration_Examples](http://wiki.desmume.org/index.php?title=Installing_DeSmuME_from_source_on_Linux#Build_Configuration_Examples)

Closing, due to user error.

**Comment by petran79** [comment]
Problem is I am on OpenSUSE and some libraries are not available at all. Eg I can not find libagg in repositories

**Comment by zeromus** [comment]
Why haven't we vendored libagg yet? That thing is basically erased from the ecosystem now

**Comment by rofl0r** [comment]
fwiw, i disabled libagg in my linux build. @rogerman mentioned on IRC that he was working on some replacement that's currently used in cocoa port and has the potential of running on GPU.

**Comment by rofl0r** [comment]
another thing i noticed is that in the autoconf build opengl is by default disabled. i had to explicitily add --enable-opengl and rebuild. IIRC in the past it was automatically enabled, if detected.

**Comment by rofl0r** [comment]
@petran79 note that the github CI automatically upload builds for some platforms. you gotta click on actions, then select one of the items in the list, then scroll down to artifacts. as an example: https://github.com/TASEmulators/desmume/actions/runs/11577216202 . though currently it seems to lack opengl support for GTK due to what i mentioned above. either autoconf should be fixed to automatically enable gl if detected, or --enable-gl be added to the github action.

**Comment by petran79** [comment]
thanks.I do not have issues compiling the application on a laptop with Linux Mint as it shares the same libraries and Opengl is enabled. I'll try the same on Opensuse, trying to skip libagg

**Comment by rogerman** [comment]
@petran79, you'll need to install the "libGL.so" for standard OpenGL rendering or "libGLESv2.so" for OpenGL ES rendering, as well as an additional library for context creation if you don't want to do context creation in SDL -- "libGLX.so" for a GLX context or "libEGL.so" for an EGL context. Do note that "libagg.so" has nothing to do with OpenGL rendering -- that is just for rendering the HUD on top of the final video output, and has nothing to do with 3D rendering.

@rofl0r, the GPU-based HUD rendering code that is used for the Cocoa port is something I don't want to promote just yet as it lacks feature parity with our current libagg-based HUD rendering code, preventing my GPU-based HUD rendering code from being a drop-in replacement. There is actually a long road ahead before feature parity occurs, so don't hold your breath on the GPU-based HUD rendering code!
