### ISSUE TITLE
Sacred Gold Romhack keeps crashing at olivine city

### ISSUE THREAD

**Issue by JustaRandomGuyef3e** [TASEmulators/desmume#857]
## State your operating system:
Windows

## DesMuME version
e.g. 0.9.13 

## Isse
type here what's bothering you, in a detailed manner.

Playing a Sacred Gold Romhack, when i enter olivine city and passing the gym someone leaves te gym and when te doors open my game freezes. i have tried the game fixes that are recommended but nothing seems te help.

**Comment by zeromus** [comment]
we don't support buggy romhacks. get support from the hack vendor. but as general advice: stop using savestates. save in-game frequently, and close the emulator. Also stop using an ancient version of the emulator, since newer versions (past several years) don't suffer from this problem so much in HeartGold.
