### ISSUE TITLE
Request: Do not overwrite battery save when loading state

### ISSUE THREAD

**Issue by Shananiganeer** [TASEmulators/desmume#876]
## State your operating system:
Windows

## DesMuME version
0.9.13

## Issue
Please add a config option to NOT overwrite battery saves when loading a savestate, and make that the default behavior. I realize that loading a savestate will necessarily load that state's save into memory, but it doesn't follow that this must overwrite the data saved to disk if there isn't a corresponding in-game save.

The current functionality is at best misleadingly named, as I suspect exceedingly few uninformed people would predict a "Load" operation will write to disk. Judging by the number of users that have not only run into the issue, but then posted online about it, that seems to be the case and this would be a big win as far as dev time to user impact.

If the data on disk absolutely needs to be overwritten when loading the state, then instead please add a config option to back up an existing battery save when loading a savestate.

I am aware that it is recommended to not use savestates to save progress, especially not to mix them with in-game saves, and I do not use them like that, but it is currently way too easy to misclick and destroy your own progress. Currently, users must either unbind the savestate buttons or manually delete states from disk after their temporary need is over to protect themselves.

**Comment by rogerman** [comment]
You cannot assume that battery saves only contain the user's save data. In fact, many games save internal settings and parameters beyond just the user's save data. For this reason, the battery save itself MUST be a part of the save state. If you decouple the battery save data from the save state, you could very well be introducing a whole new slew of data corruption issues.

So... no, we will NOT include an option to decouple the battery save from the save state. Overwriting the battery save when loading a save state is REQUIRED for data integrity.

@Shananiganeer, if you are concerned about accidentally overwriting a battery save with a save state, then you could use the File > Save State As menu option to make a "master" save state file for yourself at regular intervals during the game (probably best done after you've performed an in-game save). This way, you can't accidentally lose your battery saves because your master save state files will contain the battery save that you need. You can make as many of these save state files through File > Save State As as you like -- you are not limited to 10 slots. You can do this for both the Windows and Mac versions of DeSmuME.

Closing, since fulfilling this request would eventually lead to more harm than good.

**Comment by Shananiganeer** [comment]
From the outside it didn't seem like much of an ask for the data to be kept in RAM versus constantly accessing the disk or to clone the data to a temporary hidden file while running instead of the real one, but this is meant to be a fairly simple request and it sounds like there is enough of a technical reason to leave that in place.

I did consider that when posting, so please address the second half of my request.

> If the data on disk absolutely needs to be overwritten when loading the state, then instead please add a config option to back up an existing battery save when loading a savestate.

My thinking was simply copying the existing battery save to <ROM name>-backup.dsv when overwriting to give a disaster recovery option for an unintentional keypress.

For clarity, I already backup my saves on a schedule for an additional layer of protection due to previous experience using DesMuME over the years. I have recently recommended DesMuME to friends and forgot about this external solution and they ended up wiping progress prompting the request.

If this is still too much of an ask, I'll see if I can implement it myself and submit a PR.

**Comment by rogerman** [comment]
An automatic backup of the .dsv right before loading a save state has merit. Make a new request for this feature instead, as we are not decoupling the battery save file from the save state for the reasons mentioned in my previous post.

And AFAIK, the nightly Windows port already has an alternate feature in that it can generate automatic save states. I don't remember how to use that feature off the top of my head, but it is something looking into.

**Comment by zeromus** [comment]
If the option is added, it should be called "clobber's lament" because that's the terminology mednafen uses, and mednafen has thought about it more than anyone else except for me.

We can't change the default behavior because desmume is used by millions of people with learning disabilities. 

An automatic backup for .dsv is redundant. There's already a feature for automatic STATE backup, which is enabled by default (on windows, at least). This is better and protects against more mistakes with one feature. The .dsv is inside it and can be recovered simply by loading the state and letting the .dsv dump out again. It's even more useful for recovering .dsv, even if that's all you want, because you can load the states one by one and find the one in the condition you want. Doing this same thing with .dsv is quite cumbersome. 

If automatic savestate backup is missing from non-windows ports, it should be enabled there. 

For anyone making a new emulator: both ways of managing .dsv (dumping it when loading states, NOT dumping it when loading states) are bad for their own reasons, and the whole paradigm needs to be jettisoned. Instead, the user needs to take responsibility for exporting their save data whenever they want to and it seems sensible.

**Comment by Shananiganeer** [comment]
> An automatic backup for .dsv is redundant. There's already a feature for automatic STATE backup, which is enabled by default (on windows, at least). This is better and protects against more mistakes with one feature. The .dsv is inside it and can be recovered simply by loading the state and letting the .dsv dump out again. It's even more useful for recovering .dsv, even if that's all you want, because you can load the states one by one and find the one in the condition you want. Doing this same thing with .dsv is quite cumbersome.

If there is already an automatic backup being made when loading a save state, that's fantastic and maybe should be added to the FAQ or otherwise clearly communicated. I had noticed the state backups folders and incorrectly assumed they were being created on save instead of on load. At its core, my request is to not irreversibly delete data, in particular when it's not clear that there will be a deletion, and I'm quite happy it's already moot.

**Comment by zeromus** [comment]
I'll gladly take suggestions on what to write in the faq.
